Content:

  Global:
  
    main:                   # the main module is required, and must not be removed.
      components:
        header:
        footer:
    News:
      page: true
      components:
        list:
        show:
    Factorys:
          page: true
          components:
            list:
            show:
    Podrazdelenia:
          page: true
          components:
            list:
            show: