<?php

/**
 * BaseNews
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property clob $body
 * @property integer $image
 * @property boolean $is_active
 * @property DmMedia $Image
 * 
 * @method string  getTitle()     Returns the current record's "title" value
 * @method clob    getBody()      Returns the current record's "body" value
 * @method integer getImage()     Returns the current record's "image" value
 * @method boolean getIsActive()  Returns the current record's "is_active" value
 * @method DmMedia getImage()     Returns the current record's "Image" value
 * @method News    setTitle()     Sets the current record's "title" value
 * @method News    setBody()      Sets the current record's "body" value
 * @method News    setImage()     Sets the current record's "image" value
 * @method News    setIsActive()  Sets the current record's "is_active" value
 * @method News    setImage()     Sets the current record's "Image" value
 * 
 * @package    diem_uz
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseNews extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('news');
        $this->hasColumn('title', 'string', 120, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 120,
             ));
        $this->hasColumn('body', 'clob', null, array(
             'type' => 'clob',
             'extra' => 'markdown',
             ));
        $this->hasColumn('image', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('DmMedia as Image', array(
             'local' => 'image',
             'foreign' => 'id'));
    }
}