<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version2 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('news', 'news_image_dm_media_id', array(
             'name' => 'news_image_dm_media_id',
             'local' => 'image',
             'foreign' => 'id',
             'foreignTable' => 'dm_media',
             ));
        $this->addIndex('news', 'news_image', array(
             'fields' => 
             array(
              0 => 'image',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('news', 'news_image_dm_media_id');
        $this->removeIndex('news', 'news_image', array(
             'fields' => 
             array(
              0 => 'image',
             ),
             ));
    }
}