<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version3 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->changeColumn('factorys', 'body', 'clob', '', array(
             'extra' => 'ckeditor',
             ));
        $this->changeColumn('news', 'body', 'clob', '', array(
             'extra' => 'ckeditor',
             ));
        $this->changeColumn('podrazdelenia', 'body', 'clob', '', array(
             'extra' => 'ckeditor',
             ));
    }

    public function down()
    {

    }
}