<ul class="factory_body" style="margin-top: -40px;">
	<h1 style="padding-top: 40px;">ЗАО «Фоминская дубрава»</h1>
	<p>
		Александров С.А.
		(86385)54342
		f.dubrava@rambler.ru
	</p>

	<h1>ЗАО «Зеленая роща»</h1>
	<p>
		Клевцов В.В.
		(86385)50362
		zel-ros@yandex.ru
	</p>

	<h1>ООО «ЦАИ»</h1>
	<p>
		Кипоть С.Н.
		391040
		centragroinvest@pbox.ttn.ru
	</p>

	<h1>Филиал «Русь»</h1>
	<p>
		(86387)46167
	</p>

	<h1>ОАО «Чертковский элеватор»</h1>
	<p>
		Легкоконец Г.К.
		(86387)21412
		chert_elevator@mail.ru
	</p>

	<h1>ОАО «Мальчевский элеватор»</h1>
	<p>
		Ганноченко В.Л.
		(86385)50577
		mal-el@mail.ru
	</p>
	<br>
</ul>