<div class="main_block main_block_left">
	<h1>Группа компаний<br> «ЮГ-ЗЕРНО»</h1>
	<br>
	Группа компаний «ЮГ-ЗЕРНО» является одним из крупнейших сельскохозяйственных холдингов Юга России.
	Возглавляющая холдинг управляющая компания  ООО «ЮГ-ЗЕРНО» была создана в 1996 году.
	За 16 лет успешной деятельности  на рынке в ГК «ЮГ-ЗЕРНО» вошли предприятия, специализирующиеся на производстве, переработке сельскохозяйственной продукции.
	<br><br>
	<h2>ООО «ЮГ-ЗЕРНО»</h2>
	Адрес: 347936, г. Таганрог, Ростовской области,
	ул. Л. Чайкиной, 328
	Тел.(8634) 37-63-73, 37-63-63
	Вид деятельности: оптовая торговля
	зерновыми, масленичными и прочими культурами
	<h2>Генеральный директор <br>Бердутин Александр Павлович</h2>
</div>

<div class="main_block main_block_right">
	<h1>Основными видами деятельности<br> ГК «ЮГ-ЗЕРНО» являются:</h1>
	<ul>
		<li>закупка и реализация сельхозпродукции на внутреннем рынке и на экспорт;</li>
		<li>хранение сельхозпродукции и предоставление услуг элеваторов;</li>
		<li>растениеводство и животноводство;</li>
		<li>переработка сельхозпродукции;</li>
		<li>инвестирование в жилую и коммерческую недвижимость.</li>
	</ul>
</div>

<div id="gal_1_1" class="main_galery" style=" background: url('img/280x280-1-1.png') no-repeat;"></div>
<div id="gal_1_2" class="main_galery" style=" background: url('img/280x280-1-2.png') no-repeat; display: none;"></div>
<div id="gal_1_3" class="main_galery" style=" background: url('img/280x280-1-3.png') no-repeat; display: none;"></div>
<div id="gal_1_4" class="main_galery" style=" background: url('img/280x280-1-4.png') no-repeat; display: none;"></div>
<div id="gal_1_5" class="main_galery" style=" background: url('img/280x280-1-5.png') no-repeat; display: none;"></div>
<div id="gal_1_6" class="main_galery" style=" background: url('img/280x280-1-6.png') no-repeat; display: none;"></div>

<div class="grey_line" style="width: 720px;"></div>

<br>

<div id="gal_2_1" class="main_galery2" style="margin-top: -50px; background: url('img/280x280-2-1.png') no-repeat;"></div>
<div id="gal_2_2" class="main_galery2" style="margin-top: -50px; background: url('img/280x280-2-2.png') no-repeat; display: none;"></div>
<div id="gal_2_3" class="main_galery2" style="margin-top: -50px; background: url('img/280x280-2-3.png') no-repeat; display: none;"></div>
<div id="gal_2_4" class="main_galery2" style="margin-top: -50px; background: url('img/280x280-2-4.png') no-repeat; display: none;"></div>

<div class="history_main">
	<div class="mini_logo"></div>
	<div class="history_img"></div>
	<h1>
		История<br>
		ГК "ЮГ-ЗЕРНО"
	</h1>
	<p style="width: 300px;">
		Группа компаний ООО "ЮГ-ЗЕРНО" работает на российском рынке с мая 1996-го года.
		За время своей деятельности ООО "ЮГ-ЗЕРНО" охватила большое число регионов страны
		и вышла на мировой рынок, экспортируя сельскохозяйственную продукцию.
	</p>
	<p style="width: 720px;">
		Основными направлениями работы ООО "ЮГ-ЗЕРНО" являются производство и переработка сельскохозяйственной продукции
		и ее реализация на внутреннем и внешнем рынках. Расположение в Ростовской области, одном из ведущих
		зернопроизводящих регионов России, дает возможность использовать основные виды транспортного сообщения (морские пути, железнодорожные узлы,
		 автомагистрали), наличие собственных посевных площадей и элеваторов позволяет самостоятельно осуществлять производство, хранение и последующую
		реализацию продукции.
	</p>
</div>
<div class="grey_line"></div>

<h1 style="margin-left: 20px; font-size: 16px; font-family: Arial; color: #545250;">Схема товарно-денежных <br>потоков ГК "ЮГ-ЗЕРНО"</h1>
<div class="schema_main"></div>

<script>
	var gal1_id;
	var gal2_id;
	$(document).ready(function() {
		setInterval(interval, 5000);
	});

	function interval() {
		gal_1 ();
		gal_2 ();
	}

	function gal_1() {
		gal = $(".main_galery:visible").attr("id");
		gal1_id = gal.charAt(gal.length-1)*1;
		$("#gal_1_"+gal1_id).fadeOut(500,function(){
			if(gal1_id==6){
				gal1_id=0;
			}
			gal1_id++;
			$("#gal_1_"+gal1_id).fadeIn(500);
		})
	}


	function gal_2() {
		gal = $(".main_galery2:visible").attr("id");
		gal2_id = gal.charAt(gal.length-1)*1;
		$("#gal_2_"+gal2_id).slideUp(500,function(){
			if(gal2_id==4){
				gal2_id=0;
			}
			gal2_id++;
			$("#gal_2_"+gal2_id).slideDown(500);
		})
	}
</script>
